/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Chair.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Chair.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ASSET.geometry} material={materials.Blinn3} />
    </group>
  )
}

useGLTF.preload('/Chair.gltf')
